name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag helloworld:latest
    - name: Container image scan
      uses: azure/container-scan@v0
      with:
           image-name: helloworld:latest 
